# Generated by Django 4.2.5 on 2023-09-24 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='title',
            new_name='cityName',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='description',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='completed',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='maxTemp',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='minTemp',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
