# Generated by Django 4.2.5 on 2023-09-24 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weather_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
