# Generated by Django 4.2.5 on 2023-09-24 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weather_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='weather',
        ),
        migrations.AddField(
            model_name='weather',
            name='weatherDesc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='weatherIcon',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='weatherName',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
