# Generated by Django 4.2.5 on 2023-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_weather_weather_weather_weatherdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='maxTemp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='minTemp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weatherIcon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weatherName',
            field=models.CharField(max_length=100),
        ),
    ]
